EmployeeManagment/ViewModels/CreateRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManagment.ViewModels
{
    public class CreateRoleViewModel
    {
        [Required]
        public string RoleName { get; set; }
    }
}

EmployeeManagment/ViewModels/EditRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManagment.ViewModels
{
    public class EditRoleViewModel
    {
        public string Id { get; set; }

        [Required(ErrorMessage = "Role name is required")]
        public string RoleName { get; set; }

        public List<string> Users { get; set; } = new List<string>();
    }
}

EmployeeManagment/ViewModels/EditUserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManagment.ViewModels
{
    public class EditUserViewModel
    {
        public string Id { get; set; }
        [Required]
        public string UserName { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        public string City { get; set; }
        public IList<string> Roles { get; set; } = new List<string>();
        public IList<string> Claims { get; set; } = new List<string>();
    }
}

EmployeeManagment/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EmployeeManagment.Models;
using EmployeeManagment.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EmployeeManagment.Controllers
{
    [Authorize(Policy = "AdminRolePolicy")]
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public AdministrationController(RoleManager<IdentityRole> roleManager, 
                                        UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult ListUsers()
        {
            var users = userManager.Users;
            return View(users);
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with id {id} not found";
                return View("NotFound");
            }

            var userRoles = await userManager.GetRolesAsync(user);
            var userClaims = await userManager.GetClaimsAsync(user);

            var model = new EditUserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                UserName = user.UserName,
                City = user.City,
                Roles = userRoles,
                Claims = userClaims.Select(c => c.Type +": "+ c.Value).ToList()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserViewModel model)
        {
            var user = await userManager.FindByIdAsync(model.Id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with id {model.Id} not found";
                return View("NotFound");
            }
            else
            {
                user.Email = model.Email;
                user.UserName = model.UserName;
                user.City = model.City;

                var result = await userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }

                return View(model);
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with id {id} not found";
                return View("NotFound");
            }
            else
            {
                var result = await userManager.DeleteAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return RedirectToAction("ListUsers");
            }
        }

        [HttpGet]
        [Authorize(Policy = "CreateRolePolicy")]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Policy = "CreateRolePolicy")]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if(ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.RoleName
                };

                IdentityResult result = await roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("listroles", "administration");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult ListRoles()
        {
            var roles = roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with id {id} not found";
                return View("NotFound");
            }

            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name
            };

            foreach (var user in await userManager.Users.ToListAsync())
            {
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with id {model.Id} not found";
                return View("NotFound");
            }
            else
            {
                role.Name = model.RoleName;
                var result = await roleManager.UpdateAsync(role);

                if(result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }
        }

        [HttpPost]
        [Authorize(Policy = "DeleteRolePolicy")]
        public async Task<IActionResult> DeleteRole(string id)
        {
            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with id {id} not found";
                return View("NotFound");
            }
            else
            {
                try
                {
                    var result = await roleManager.DeleteAsync(role);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("ListRoles");
                    }

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }

                    return RedirectToAction("ListRoles");
                }
                catch (DbUpdateException)
                {
                    ViewBag.ErrorMessage = "There's users under this role";
                    return View("Error");
                }
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.RoleId = roleId;

            var role = await roleManager.FindByIdAsync(roleId);

            if(role == null)
            {
                ViewBag.ErrorMessage = $"Role with id {roleId} not found";
                return View("NotFound");
            }

            var model = new List<UserRoleViewModel>();

            foreach (var user in await userManager.Users.ToListAsync())
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }

                model.Add(userRoleViewModel);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with id {roleId} not found";
                return View("NotFound");
            }

            for(int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result;

                if (model[i].IsSelected == true && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if(!model[i].IsSelected == true && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                        return RedirectToAction("EditRole", new { Id = roleId });
                }
            }

EmployeeManagment/Views/Administration/CreateRole.cshtml
@model CreateRoleViewModel

@{
    ViewBag.Title = "Create New Role";
}

<h3 class="mt-3 clr-green">@ViewBag.Title</h3>

<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div class="form-group">
                <label asp-for="RoleName"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-success">Create</button>
            <div asp-validation-summary="All" class="text-danger"></div>
        </form>
    </div>
</div>

EmployeeManagment/Views/Administration/EditRole.cshtml
@model EditRoleViewModel

@{
    ViewBag.Title = "Edit Role";
}

<h3 class="mt-3">@ViewBag.Title</h3>

<form method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" class="form-control" disabled />
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="RoleName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RoleName" class="form-control" />
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-success">
                Update
            </button>
            <a asp-controller="Administration" asp-action="ListRoles" class="btn btn-outline-success">
                Cancel
            </a>
        </div>
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="card thm-gray">
        <h5 class="card-header">
            Users in this role
        </h5>
        <div class="card-body">
            @if (Model.Users.Any())
            {
                foreach (var user in Model.Users)
                {
                    <h5 class="card-title">@user</h5>
                }
            }
            else
            {
                <h5 class="card-title">There is no users under this role</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-controller="Administration" asp-action="EditUsersInRole" asp-route-roleId="@Model.Id"
               class="btn btn-outline-success" style="width: auto">
                Add/Remove Users
            </a>
        </div>
    </div>
</form>

EmployeeManagment/Views/Administration/EditUser.cshtml
@model EditUserViewModel

@{ 
    ViewBag.Title = "Edit User";
}

<h3 class="mt-3 clr-green">@ViewBag.Title</h3>

<form method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" class="form-control" disabled />
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="UserName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="UserName" class="form-control" />
            <span asp-validation-for="UserName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="City" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="City" class="form-control" />
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-success">
                Update
            </button>
            <a asp-controller="Administration" asp-action="ListUsers" class="btn btn-outline-success">
                Cancel
            </a>
        </div>
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="card thm-gray mb-2">
        <h3 class="card-header">
            User Roles
        </h3>
        <div class="card-body">
            @if (Model.Roles.Any())
            {
                foreach (var role in Model.Roles)
                {
                    <h5 class="card-title">@role</h5>
                }
            }
            else
            {
                <h5 class="card-title">There's no roles</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-controller="Administration" asp-action="ManageUserRoles" asp-route-id="@Model.Id" 
               class="btn btn-outline-success">
                Manage
            </a>
        </div>
    </div>
    <div class="card thm-gray">
        <h3 class="card-header">
            User Claims
        </h3>
        <div class="card-body">
            @if (Model.Claims.Any())
            {
                foreach (var claim in Model.Claims)
                {
                    <h5 class="card-title">@claim</h5>
                }
            }
            else
            {
                <h5 class="card-title">There's no claims</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-controller="Administration" asp-action="ManageUserClaims" asp-route-id="@Model.Id" 
               class="btn btn-outline-success">
                Manage
            </a>
        </div>
    </div>
</form>

EmployeeManagment/Views/Administration/EditUsersInRole.cshtml
@model List<UserRoleViewModel>

@{
    var roleId = ViewBag.RoleId;
}

<form method="post">
    <div class="card thm-gray mt-3">
        <h5 class="card-header clr-green">
            Add or remove users from this role
        </h5>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check m-1">
                    <input asp-for="@Model[i].UserId" type="hidden" />
                    <input asp-for="@Model[i].UserName" type="hidden" />
                    <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                    <label asp-for="@Model[i].IsSelected" class="form-check-label">
                        @Model[i].UserName
                    </label>
                </div>
            }
        </div>
        <div class="card-footer">
            <button type="submit" class="btn btn-success">
                Update
            </button>
            <a asp-controller="Administration" asp-action="EditRole" asp-route-id="@roleId" class="btn btn-outline-success">
                Cancel
            </a>
        </div>
    </div>
</form>

EmployeeManagment/Views/Administration/ListRoles.cshtml
@model IEnumerable<IdentityRole>
@inject IAuthorizationService authorizationService

@{
    ViewBag.Title = "Roles";
}

<h3 class="mt-3 clr-green">@ViewBag.Title</h3>

@if (Model.Any())
{
    <a asp-controller="Administration" asp-action="CreateRole" class="btn btn-success mb-2">
        Add New
    </a>
    @foreach (var role in Model)
    {
        <div class="card mb-3 thm-gray">
            <h5 class="card-header">
                Role ID: @role.Id
            </h5>
            <div class="card-body">
                <h5 class="card-title">@role.Name</h5>
            </div>
            <div class="card-footer">
                <form asp-controller="Administration" asp-action="DeleteRole" asp-route-id="@role.Id" method="post">

                    @if ((await authorizationService.AuthorizeAsync(User, "EditRolePolicy")).Succeeded)
                    {
                        <a asp-controller="Administration" asp-action="EditRole" asp-route-id="@role.Id"
                           class="btn btn-outline-success">
                            Edit
                        </a>
                    }
                    else
                    {
                        <button class="btn btn-secondary" disabled>
                            Edit
                        </button>
                    }

                    @if ((await authorizationService.AuthorizeAsync(User, "DeleteRolePolicy")).Succeeded)
                    {
                        <span id="deleteSpan_@role.Id">
                            <span class="btn btn-danger" onclick="confirmDelete('@role.Id', true)">
                                Delete
                            </span>
                        </span>
                        <span id="confirmDeleteSpan_@role.Id" style="display: none">
                            <span>Are you sure?</span>
                            <button type="submit" class="btn btn-danger">
                                Yes
                            </button>
                            <span class="btn btn-outline-success" onclick="confirmDelete('@role.Id', false)">
                                No
                            </span>
                        </span>
                    }
                    else
                    {
                        <button class="btn btn-secondary" disabled>
                            Delete
                        </button>
                    }

                </form>
            </div>
        </div>
    }
}
else
{
    <div class="card thm-gray">
        <h5 class="card-header">
            No roles created yet
        </h5>
        <div class="card-body">
            <div class="card-title">
                Use button below to create a role
            </div>
            <a asp-controller="Administration" asp-action="CreateRole" class="btn btn-success">
                Create
            </a>
        </div>
    </div>
}

@section Scripts {
    <script src="~/js/CustomScript.js"></script>
}

EmployeeManagment/Views/Administration/ListUsers.cshtml
@model IEnumerable<ApplicationUser>

@{
    ViewBag.Title = "Users";
}

<h3 class="mt-3 clr-green">@ViewBag.Title</h3>

@if (Model.Any())
{
    <a asp-controller="Account" asp-action="Register" class="btn btn-success mb-2">
        Add New
    </a>
    @foreach (var user in Model)
    {
        <div class="card mb-3 thm-gray">
            <h5 class="card-header">
                User ID: @user.Id
            </h5>
            <div class="card-body">
                <h5 class="card-title">@user.UserName</h5>
            </div>
            <div class="card-footer">
                <form asp-controller="Administration" asp-action="DeleteUser" asp-route-id="@user.Id" method="post">
                    <a asp-controller="Administration" asp-action="EditUser" asp-route-id="@user.Id"
                       class="btn btn-outline-success">
                        Edit
                    </a>
                    <span id="deleteSpan_@user.Id">
                        <span class="btn btn-danger" onclick="confirmDelete('@user.Id', true)">
                            Delete
                        </span>
                    </span>
                    <span id="confirmDeleteSpan_@user.Id" style="display: none">
                        <span>Are you sure?</span>
                        <button type="submit" class="btn btn-danger">
                            Yes
                        </button>
                        <span class="btn btn-outline-success" onclick="confirmDelete('@user.Id', false)">
                            No
                        </span>
                    </span>
                </form>
            </div>
        </div>
    }
}
else
{
    <div class="card thm-gray">
        <h5 class="card-header">
            No users created yet
        </h5>
        <div class="card-body">
            <div class="card-title">
                Use button below to create a user
            </div>
            <a asp-controller="Account" asp-action="Register" class="btn btn-success">
                Create
            </a>
        </div>
    </div>
}

@section Scripts {
    <script src="~/js/CustomScript.js"></script>
}

EmployeeManagment/Views/Administration/ManageUserClaims.cshtml
@model UserClaimsViewModel

<form method="post">
    <div class="card thm-gray mt-3">
        <h3 class="card-header">
            Manage User Claims
        </h3>
        <div class="card-body">
            <input asp-for="@Model.UserId" type="hidden" />
            @for (int i = 0; i < Model.Claims.Count; i++)
            {
                <div class="form-check m-1">
                    <input asp-for="@Model.Claims[i].ClaimType" type="hidden" />
                    <input asp-for="@Model.Claims[i].IsSelected" class="form-check-input" />
                    <label asp-for="@Model.Claims[i].IsSelected" class="form-check-label">
                        @Model.Claims[i].ClaimType
                    </label>
                </div>
            }
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
        <div class="card-footer">
            <input class="btn btn-success" type="submit" value="Update" />
            <a asp-controller="Administration" asp-action="EditUser" asp-route-id="@Model.UserId"
               class="btn btn-outline-success">
                Cancel
            </a>
        </div>
    </div>
</form>

EmployeeManagment/Views/Administration/ManageUserRoles.cshtml
@model List<UserRolesViewModel>

@{ 
    var userId = ViewBag.UserId;
}

<form method="post">
    <div class="card thm-gray mt-3">
        <h3 class="card-header">
            Manage User Roles
        </h3>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[i].RoleId" />
                    <input type="hidden" asp-for="@Model[i].RoleName" />
                    <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                    <label asp-for="@Model[i].IsSelected" class="form-check-label">
                        @Model[i].RoleName
                    </label>
                </div>
            }
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
        <div class="card-footer">
            <input class="btn btn-success" type="submit" value="Update" />
            <a asp-controller="Administration" asp-action="EditUser" asp-route-id="@userId"
               class="btn btn-outline-success">
                Cancel
            </a>
        </div>
    </div>
</form>